/* Auto-generated by scripts/compile-contracts.mjs — do not edit by hand. */

import IdentityRegistryJson from "./IdentityRegistry.json";
export const IdentityRegistryArtifact = IdentityRegistryJson as {
  contractName: string;
  abi: readonly unknown[];
  bytecode: `0x${string}`;
};

import SecurityTokenJson from "./SecurityToken.json";
export const SecurityTokenArtifact = SecurityTokenJson as {
  contractName: string;
  abi: readonly unknown[];
  bytecode: `0x${string}`;
};
